"""AI contracts for Adaptix platform."""

from .capabilities import (
    AIProviderStatus,
    AICapabilityRegistryEntry,
    AITextGenerationRequest,
    AITextGenerationResponse,
    AIReadinessAssessment,
    AIDraftNarrative,
    AIHumanReviewRequirement,
    AIAuditRecord,
    AISourceField,
    AIRedactionPolicy,
    AIGeneratedTextMetadata,
    AIRiskLevel,
)
from .smart_text import (
    SmartTextRequest,
    SmartTextResponse,
    SmartTextAuditEntry,
    SmartTextModule,
    SmartTextCapability,
)
from .audit import AIAuditPolicy, AIAuditEvent, AIAuditEventType
from .connection import (
    AI_CONNECTION_CONTRACT_VERSION,
    AIProviderKey,
    AIExecutionMode,
    ExternalClientType,
    PolicyDecision,
    ToolRiskClass,
    DataClassification,
    EffectivePolicyDecision,
    PolicyReasonCode,
    tool_risk_rank,
    tool_is_write,
    data_classification_allows_mcp,
    data_classification_is_phi,
    allow,
    deny,
    approval_required,
)
from .mcp_tools import (
    MCP_TOOL_CONTRACT_VERSION,
    ReadOrWrite,
    MCPToolContract,
    MCPToolContractError,
    FORBIDDEN_TOOL_NAMES,
)

__all__ = [
    "AIProviderStatus",
    "AICapabilityRegistryEntry",
    "AITextGenerationRequest",
    "AITextGenerationResponse",
    "AIReadinessAssessment",
    "AIDraftNarrative",
    "AIHumanReviewRequirement",
    "AIAuditRecord",
    "AISourceField",
    "AIRedactionPolicy",
    "AIGeneratedTextMetadata",
    "AIRiskLevel",
    "SmartTextRequest",
    "SmartTextResponse",
    "SmartTextAuditEntry",
    "SmartTextModule",
    "SmartTextCapability",
    "AIAuditPolicy",
    "AIAuditEvent",
    "AIAuditEventType",
    # AI & Agent Connection control plane (v1)
    "AI_CONNECTION_CONTRACT_VERSION",
    "AIProviderKey",
    "AIExecutionMode",
    "ExternalClientType",
    "PolicyDecision",
    "ToolRiskClass",
    "DataClassification",
    "EffectivePolicyDecision",
    "PolicyReasonCode",
    "tool_risk_rank",
    "tool_is_write",
    "data_classification_allows_mcp",
    "data_classification_is_phi",
    "allow",
    "deny",
    "approval_required",
    "MCP_TOOL_CONTRACT_VERSION",
    "ReadOrWrite",
    "MCPToolContract",
    "MCPToolContractError",
    "FORBIDDEN_TOOL_NAMES",
]
