"""Adaptix Synapse Fabric canonical contracts (SYN-001).

LAW SYN-001: integrate capabilities, not manufacturers. Manufacturer and
protocol differences terminate at the Adaptix driver layer (transport and
protocol drivers in Adaptix-Integrations-Service ``connector_sdk``); above it
only these versioned capability, signal, evidence, session, provenance and
edge contracts exist. Nothing in this package names a manufacturer as a type,
and nothing expresses a command to a medical device: the medical-device
command plane is forbidden in v1.

Pipeline these contracts carry, end to end::

    Physical Source -> Synapse Edge -> Transport Driver -> Protocol Driver
    -> Device Genome -> Signal Compiler -> Evidence Ledger -> Device Truth
    -> Care Session Binder (ePCR) -> ePCR projection / downstream

This package defines shapes only; it runs no Synapse behaviour. Import from
the subpackage root::

    from adaptix_contracts.synapse import ClinicalSignalEnvelope, DeviceGenome
"""

from adaptix_contracts.synapse.devices import (
    COMPAT_DRIVER_PACK_PREFIX,
    DeviceAdapterRef,
    DeviceCapabilityProfile,
    DeviceClass,
    DeviceGenome,
    DeviceIdentity,
    DriverPackId,
    DriverPackSupport,
    compute_physical_identity_hash,
)
from adaptix_contracts.synapse.edge import (
    EDGE_BATCH_MAX_RECORDS,
    SUPPORTED_EDGE_PROTOCOL_VERSIONS,
    SYNAPSE_EDGE_PROTOCOL_VERSION,
    EdgeBatch,
    EdgeBatchAck,
    EdgeClockMetadata,
    EdgeHeartbeat,
    EdgeInstanceRegistration,
    EdgeProtocolNegotiation,
    EdgeProtocolOffer,
    EdgeProtocolVersion,
    EdgeRecordAck,
    EdgeSignalRecord,
    EdgeTransportStatus,
    advance_contiguous_watermark,
    select_edge_protocol_version,
)
from adaptix_contracts.synapse.enums import (
    EXTERNAL_WAIT_DRIVER_PACK_STATUSES,
    FORBIDDEN_CONTROL_CAPABILITIES,
    RETRYABLE_EDGE_REJECTIONS,
    SIGNAL_KIND_REQUIRED_CAPABILITY,
    DeploymentProfile,
    DriverPackSupportStatus,
    DriverPackTier,
    EdgeClockSource,
    EdgeProtocolRefusalReason,
    EdgeRecordOutcome,
    EdgeRecordRejectionReason,
    EdgeRuntimeHealth,
    ProtocolKind,
    SynapseAlertCondition,
    SynapseAlertPriority,
    SynapseAlertState,
    SynapseConnectionState,
    SynapseDeviceCapability,
    SynapseForbiddenControlCapability,
    SynapseMeasurementValidity,
    SynapseQualityFlag,
    SynapseRailResolution,
    SynapseRailType,
    SynapseReplayFailureReason,
    SynapseReplayReason,
    SynapseReplayStatus,
    SynapseSessionState,
    SynapseSessionType,
    SynapseSignalKind,
    SynapseTherapyEventPhase,
    SynapseTimeQuality,
    SynapseWaveformEncoding,
    TransportKind,
    is_forbidden_control_capability,
    normalize_capability_token,
)
from adaptix_contracts.synapse.evidence import (
    EVIDENCE_LEDGER_HASH_DOMAIN,
    EVIDENCE_MAX_BYTE_SIZE,
    DeviceEvidenceReference,
    EvidenceUploadAuthorizationRequest,
    EvidenceUploadAuthorizationResponse,
    StorageKey,
    compute_evidence_ledger_entry_sha256,
)
from adaptix_contracts.synapse.provenance import (
    REPLAY_MAX_EVIDENCE_IDS,
    AdapterKey,
    CanonicalCode,
    CorrelationId,
    ExternalKey,
    MediaType,
    ReplayEvidenceFailure,
    ReplayRequest,
    ReplayResult,
    SemanticVersion,
    Sha256Hex,
    SignalProvenance,
    SynapseId,
)
from adaptix_contracts.synapse.sessions import DeviceSessionReference
from adaptix_contracts.synapse.signals import (
    MAX_CLOCK_OFFSET_MS,
    SIGNAL_KIND_PAYLOAD_TYPES,
    SYNAPSE_SIGNAL_SCHEMA_VERSION,
    AlertPayload,
    ClinicalSignalEnvelope,
    DeviceBatteryState,
    DeviceStatePayload,
    DocumentReferencePayload,
    ObservationPayload,
    ObservationReferenceRange,
    SignalQuantity,
    SynapseSignalPayload,
    TherapyEventPayload,
    UcumUnit,
    WaveformCalibration,
    WaveformReferencePayload,
)

__all__ = [
    "COMPAT_DRIVER_PACK_PREFIX",
    "EDGE_BATCH_MAX_RECORDS",
    "EVIDENCE_LEDGER_HASH_DOMAIN",
    "EVIDENCE_MAX_BYTE_SIZE",
    "EXTERNAL_WAIT_DRIVER_PACK_STATUSES",
    "FORBIDDEN_CONTROL_CAPABILITIES",
    "MAX_CLOCK_OFFSET_MS",
    "REPLAY_MAX_EVIDENCE_IDS",
    "RETRYABLE_EDGE_REJECTIONS",
    "SIGNAL_KIND_PAYLOAD_TYPES",
    "SIGNAL_KIND_REQUIRED_CAPABILITY",
    "SUPPORTED_EDGE_PROTOCOL_VERSIONS",
    "SYNAPSE_EDGE_PROTOCOL_VERSION",
    "SYNAPSE_SIGNAL_SCHEMA_VERSION",
    "AdapterKey",
    "AlertPayload",
    "CanonicalCode",
    "ClinicalSignalEnvelope",
    "CorrelationId",
    "DeploymentProfile",
    "DeviceAdapterRef",
    "DeviceBatteryState",
    "DeviceCapabilityProfile",
    "DeviceClass",
    "DeviceEvidenceReference",
    "DeviceGenome",
    "DeviceIdentity",
    "DeviceSessionReference",
    "DeviceStatePayload",
    "DocumentReferencePayload",
    "DriverPackId",
    "DriverPackSupport",
    "DriverPackSupportStatus",
    "DriverPackTier",
    "EdgeBatch",
    "EdgeBatchAck",
    "EdgeClockMetadata",
    "EdgeClockSource",
    "EdgeHeartbeat",
    "EdgeInstanceRegistration",
    "EdgeProtocolNegotiation",
    "EdgeProtocolOffer",
    "EdgeProtocolRefusalReason",
    "EdgeProtocolVersion",
    "EdgeRecordAck",
    "EdgeRecordOutcome",
    "EdgeRecordRejectionReason",
    "EdgeRuntimeHealth",
    "EdgeSignalRecord",
    "EdgeTransportStatus",
    "EvidenceUploadAuthorizationRequest",
    "EvidenceUploadAuthorizationResponse",
    "ExternalKey",
    "MediaType",
    "ObservationPayload",
    "ObservationReferenceRange",
    "ProtocolKind",
    "ReplayEvidenceFailure",
    "ReplayRequest",
    "ReplayResult",
    "SemanticVersion",
    "Sha256Hex",
    "SignalProvenance",
    "SignalQuantity",
    "StorageKey",
    "SynapseAlertCondition",
    "SynapseAlertPriority",
    "SynapseAlertState",
    "SynapseConnectionState",
    "SynapseDeviceCapability",
    "SynapseForbiddenControlCapability",
    "SynapseId",
    "SynapseMeasurementValidity",
    "SynapseQualityFlag",
    "SynapseRailResolution",
    "SynapseRailType",
    "SynapseReplayFailureReason",
    "SynapseReplayReason",
    "SynapseReplayStatus",
    "SynapseSessionState",
    "SynapseSessionType",
    "SynapseSignalKind",
    "SynapseSignalPayload",
    "SynapseTherapyEventPhase",
    "SynapseTimeQuality",
    "SynapseWaveformEncoding",
    "TherapyEventPayload",
    "TransportKind",
    "UcumUnit",
    "WaveformCalibration",
    "WaveformReferencePayload",
    "advance_contiguous_watermark",
    "compute_evidence_ledger_entry_sha256",
    "compute_physical_identity_hash",
    "is_forbidden_control_capability",
    "normalize_capability_token",
    "select_edge_protocol_version",
]
