"""Adaptix cross-domain contract schemas.

All Pydantic models for events and read-only contracts used across domain boundaries.
"""

from adaptix_contracts.event_contracts import (
    EventSchema,
    EventMetadata,
    EventValidator,
    LocalEventConsumerRegistry,
)

# Air
from .air_contracts import (
    AirMissionCreatedEvent,
    AirMissionStatusUpdatedEvent,
    AirMissionContract,
    AirLandingZoneContract,
)

# Calendar kernel
from .calendar_contracts import (
    AdaptixCalendarAuditAction,
    AdaptixCalendarAuditEvent,
    AdaptixCalendarConflict,
    AdaptixCalendarConflictReason,
    AdaptixCalendarEvent,
    AdaptixCalendarEventStatus,
    AdaptixCalendarProduct,
    AdaptixCalendarResource,
    AdaptixCalendarResourceKind,
    CalendarAvailabilityResponse,
    CalendarAuditEntry,
    CalendarEventCreateRequest,
    CalendarEventUpdateRequest,
)

# Air Pilot
from .air_pilot_contracts import (
    PilotGoNoGoEvent,
    PilotReadinessStatus,
)

# Duty Auth
from .duty_auth_contracts import (
    FieldLoginRequest,
    FieldLoginResolved,
    CreateDutySessionRequest,
    DutySessionResponse,
    EndDutySessionRequest,
    EndDutySessionResponse,
    RevokeBadgeRequest,
    RevokeBadgeResponse,
    AuthAuditEvent,
)

# Audit
from .audit_contracts import (
    AuditActorType,
    AuditActionType,
    AuditSeverity,
    ComplianceReviewStatus,
    AuditContext,
    AuditRecord,
    PhiAccessRecord,
    SecurityEventRecord,
    ComplianceReviewItem,
    AuditRecordCreatedEvent,
    PhiAccessLoggedEvent,
    SecurityEventDetectedEvent,
    ComplianceReviewOpenedEvent,
    AuditDomainAction,
    AuditEntry,
    AuditExportFormat,
    AuditEvent,
    AuditSearchQuery,
    AuditExportRequest,
    AuditIngestRequest,
    AuditIngestResponse,
    AuditSearchResponse,
    AuditExportStatus,
    AuditExportResponse,
)

# Billing
from .billing_contracts import (
    ClaimStatus,
    DenialStatus,
    PaymentStatus,
    ClearinghouseStatus,
    LiveBillingClearinghouse,
    ClearinghouseProvider,
    MigrationSourceVendor,
    PayerType,
    ClaimLineItem,
    AdjustmentContract,
    PayerContract,
    ClaimContract,
    DenialContract,
    PaymentContract,
    RemittanceContract,
    ClearinghouseSubmission,
    ClaimCreatedEvent,
    ClaimSubmittedEvent,
    ClaimStatusUpdatedEvent,
    DenialCreatedEvent,
    PaymentPostedEvent,
    RemittanceReceivedEvent,
)

# Billing Auth
from .billing_auth_contracts import (
    BillingRole,
    BillingPostAuthRoute,
    MFARequirement,
    SessionAnomalyState,
    BillingSignInContext,
    BillingAccessResolution,
    BillingOrgSelectorEntry,
)

# Billing Clearinghouse
from .billing_clearinghouse_contracts import (
    SubmissionStatus,
    AckType,
    StediReadinessState,
    StediWebhookVerification,
    StediReadinessBlockerOwner,
    StediMigrationMode,
    StediMigrationTransitionKind,
    StediEnrollmentTransactionType,
    StediPayerEnrollmentStatus,
    SubmissionAttemptStatus,
    RemittancePostingStatus,
    SubmissionFrequency,
    StediArtifactTransactionKind,
    StediClaimTransition,
    StediWebhookProcessingStatus,
    StediProviderRow,
    StediPayerRow,
    StediWebhookStatus,
    StediStatusBlocker,
    StediStatusResponse,
    StediAllowedTransition,
    StediMigrationModeResponse,
    StediMigrationTransitionRequest,
    StediMigrationTransitionResponse,
    StediMigrationTransitionHistoryRow,
    StediCreateEnrollmentRequest,
    StediCreateEnrollmentResponse,
    MigrationSourceClearinghouseSettingsResponse,
    MigrationSourceClearinghouseSettingsUpdate,
    SubmissionSummaryResponse,
    RemittanceSummary,
    RemittanceListResponse,
    StediServiceLineOutcome,
    StediNormalizedArtifact,
    StediNormalizationResult,
    StediWebhookReconcileOutcome,
    ClaimSubmissionRequest,
    ClaimSubmissionResponse,
    ClearinghouseAck,
    ClaimAckStatus,
    RemittanceIngestRequest,
    RemittanceClaimPayment,
    RemittanceIngestResponse,
    ClaimSubmittedToClearinghouseEvent,
    ClearinghouseAckReceivedEvent,
    RemittanceIngestedEvent,
    # Stedi inbound webhook (POST /api/v1/billing/webhooks/stedi, PR #541)
    StediWebhookEventType,
    StediWebhookRequest,
    StediWebhookAcceptedResponse,
    StediWebhookDuplicateResponse,
    StediWebhookRejectedResponse,
    # Clearinghouse retry-eligibility + operator fallback (PR #539)
    ClaimTransmissionState,
    ClaimRetryReasonCode,
    ClaimRetryEligibilityResponse,
    ClaimOperatorFallbackRequest,
    ClaimOperatorFallbackResponse,
    OperatorFallbackRefusedReasonCode,
    ClaimOperatorFallbackRefusedError,
    ClaimOperatorFallbackTargetFailedError,
)

# Billing Eligibility
from .billing_eligibility_contracts import (
    EligibilityStatus,
    CoverageLevel,
    AuthorizationStatus,
    EligibilityRequest,
    EligibilityBenefitSummary,
    EligibilityResponse,
    EligibilityCheckedEvent,
    AuthorizationStatusUpdatedEvent,
)

# Billing Portal
from .billing_portal_contracts import (
    SurfaceAvailability,
    UrgencyLevel,
    BillingPriorityQueueSummary,
    BillingBlockedClaimsSummary,
    BillingDenialQueueSummary,
    BillingAgedARSummary,
    BillingUnderpaymentSummary,
    BillingPatientFinancialSummary,
    BillingIntegrationHealthSummary,
    BillingOperatorSummary,
    BillingPortalHomeSummary,
    ClaimDefectSeverity,
    ClaimDefect,
    ClaimReadinessSummary,
    ClaimIntakeRecord,
    SubmissionAttempt,
    SubmissionTimelineEvent,
    DenialRecord,
    DenialCluster,
    DenialRootCauseSummary,
    DenialRecoveryForecast,
    FounderTenantFinancialSummary,
    FounderBillingOverview,
)

# Billing Transport
from .billing_transport_contracts import (
    TransportReadinessRequest,
    TransportReadinessResponse,
    BillingReadinessGate,
    TransportReadinessGateStatus,
    ClaimArtifactAttachRequest,
    ClaimArtifactAttachResponse,
    BillingTransportLinkEvent,
    ClaimReadinessResolvedEvent,
)

# CAD
from .cad_contracts import (
    CadCaseCreatedEvent,
    CadCaseStatusUpdatedEvent,
    CadCaseContract,
    CadUnitAssignedEvent,
)

# CAD Transport
from .cad_transport_contracts import (
    CadTransportLaneStatus,
    CadTransportLinkStatus,
    CadTransportLinkContract,
    CadDispatchReadyEntryContract,
    CadTransportExceptionEntryContract,
    CadTransportStatusSyncContract,
    ScheduledTransportLaneItem,
    DispatchReadyItem,
    CadTransportException,
    CadTransportActivateRequest,
    CadTransportActivateResponse,
    CadTransportSyncPayload,
    CadTransportSyncResponse,
    TransportActivatedEvent,
    TransportStatusSyncedEvent,
)

# Communications
from .communications_contracts import (
    NotificationRequest,
    NotificationDeliveredEvent,
    NotificationFailedEvent,
)

# Contract onboarding
from .contract_onboarding_contracts import (
    ContractLifecycleStatus,
    ContractServiceScope,
    ContractPayerMix,
    ContractPricingTerms,
    ContractBillingRules,
    ContractModuleTerms,
    ContractIntakeRequest,
    ContractRecord,
    TrustSignExecutionRequest,
    TrustSignExecutionResponse,
    TrustSignCallbackEvent,
    DropboxSignExecutionRequest,
    DropboxSignExecutionResponse,
    DropboxSignCallbackEvent,
    ContractActivationRequest,
    ContractActivationResponse,
    ContractStatusChangedEvent,
)

# Signup application creation
from .signup_contracts import (
    SIGNUP_IDEMPOTENCY_HEADER,
    SignupAgencyAddress,
    SignupApplicationCreateRequest,
    SignupApplicationCreateResponse,
    SignupIdempotencyKey,
)

# Legal execution
from .legal_execution_contracts import (
    ContractType,
    ContractStatus,
    TenantContractStatusMap,
    ContractSignatureEvent,
    ContractAccessCheckRequest,
    ContractAccessCheckResponse,
)

# Cortex (separated service)
from .cortex_contracts import (
    RecommendationRequest,
    RecommendationResponse,
)

# TrustSign (separated service)
from .trustsign_contracts import (
    SignaturePackageCreateRequest,
    SignaturePackageResponse,
)

# SageMaker (separated service)
from .sagemaker_contracts import (
    PredictionRequest,
    PredictionResponse,
)

# Gateway (separated service)
from .gateway_contracts import (
    GatewayRouteRegistryEntry,
    ForwardedRequestContext,
)

# Notification (shared service)
from .notification_contracts import (
    NotificationChannel,
    NotificationStatus,
    NotificationDeliveryStatus,
    NotificationPreference,
    NotificationTemplate,
    NotificationSendRequest,
    NotificationPreferenceSet,
    NotificationQueuedEvent,
    NotificationSentEvent,
    NotificationReadEvent,
)

# Facility (shared service)
from .facility_contracts import (
    FacilityType,
    FacilityStatus,
    FacilityContact,
    FacilityAlias,
    FacilityMapping,
    FacilityCapability,
    FacilityRecord,
    FacilitySearchRequest,
    FacilitySearchResponse,
    FacilityCreateRequest,
    FacilityUpdateRequest,
    FacilityAliasCreateRequest,
    FacilityMappingUpsertRequest,
    CmsNpiSyncRequest,
    CmsNpiSyncResult,
    FacilityRegisteredEvent,
    FacilityUpdatedEvent,
    FacilityMergedEvent,
)

# Geo (shared service)
from .geo_contracts import (
    GeoCoordinate,
    GeocodeRequest,
    GeocodeResult,
    DistanceResult,
    RouteEstimate,
    ServiceArea,
    ReverseGeocodeRequest,
    AutocompleteRequest,
    AddressSuggestion,
    AutocompleteResult,
    RouteRequest,
    DistanceRequest,
    GeoClient,
)

# SignalCore (shared service)
from .signalcore_contracts import (
    EventDeliveryStatus,
    SignalCoreEvent,
    SignalCoreTrigger,
)

# Forms (shared service)
from .forms_contracts import (
    FormFieldType,
    FormStatus,
    FormValidationRule,
    FormFieldDefinition,
    FormSchema,
    FormVersion,
    FormTemplate,
    FormValidationError,
    FormSubmission,
    FormTemplateCreateRequest,
    FormTemplateUpdateRequest,
    FormVersionCreateRequest,
    FormSubmissionCreateRequest,
    FormTemplateListResponse,
    FormSubmissionListResponse,
    FormPublishedEvent,
    FormSubmittedEvent,
)

# Reference Data (shared service)
from .reference_data_contracts import (
    ReferenceDataItem,
    ReferenceDataList,
    PayerType as ReferenceDataPayerType,
    ServiceLevel,
    StateCode,
    ReferenceDataListCreateRequest,
    ReferenceDataListUpdateRequest,
    ReferenceDataItemUpsertRequest,
    ReferenceDataQuery,
    ReferenceDataListResponse,
    ReferenceDataPublishRequest,
    ReferenceDataPublishResponse,
    ReferenceDataListPublishedEvent,
    ReferenceDataListUpdatedEvent,
)

# Payment (shared service — Stripe subscriptions)
# Concept Intelligence — terminology + graph concept contracts (Phase 2)
from .terminology_contracts import (
    ConceptType,
    ConceptStatus,
    TermType,
    MappingType,
    MappingDirection,
    ReleaseStatus,
    ReviewStatus,
    LicenseStatus,
    AssertionStatus,
    Temporality,
    Experiencer,
    Certainty,
    MatchReason,
    CrosswalkClassification,
    TerminologyEventType,
    TerminologySource,
    SourceRelease,
    Concept,
    ConceptTerm,
    SemanticType,
    TerminologyCode,
    CodeMapping,
    EvidenceSpan,
    AssertionContext,
    ConfidenceBreakdown,
    ConceptCandidate,
    ConceptResolutionRequest,
    ConceptResolutionResponse,
    AutocodeMappingCandidate,
    AutocodeConcept,
    AutocodeOutput,
    GraphConceptNode,
    GraphRelationshipProvenance,
    GraphRelationship,
    GraphRelationshipExplanation,
    TerminologyEventEnvelope,
)

# Concept Intelligence — terminology concept event contracts (SignalCore-based, v1.0)
# NOTE: this module's enum is named ``TerminologyEventType`` (publisher vocabulary)
# but is re-exported here aliased to avoid colliding with the pre-existing broader
# ``terminology_contracts.TerminologyEventType`` already on the package surface —
# same pattern as ``PayerType as ReferenceDataPayerType`` above.
from .terminology_event_contracts import (
    TerminologyEventType as TerminologyConceptEventType,
    TerminologyConceptEventPayload,
    build_terminology_event,
    validate_terminology_event,
)

from .payment_contracts import (
    SubscriptionStatus,
    InvoiceStatus,
    PaymentEventType,
    StripeCustomerRef,
    SubscriptionRef,
    InvoiceRef,
    CheckoutSessionRequest,
    CheckoutSessionResponse,
    PortalSessionRequest,
    PortalSessionResponse,
    PaymentEvent,
)

# Mailroom (shared service — PostGrid)
from .mailroom_contracts import (
    MailStatus,
    MailClass,
    MailReturnReason,
    MailRecipient,
    MailSender,
    MailPacket,
    MailDeliveryStatus,
    MailReturnStatus,
)

# RTC (shared service)
from .rtc_contracts import (
    RTCRoomStatus,
    RTCSession,
    RTCParticipantToken,
)

# Office Ally (shared service)
from .officeally_contracts import (
    OfficeAllyEnrollmentStatus,
    OfficeAllyEnrollment,
    OfficeAllySubmission,
    OfficeAllyResponse,
)

# Device (shared service)
from .device_contracts import (
    DevicePlatform,
    DeviceStatus,
    DeviceRegistration,
)

# App Access (shared service)
from .app_access_contracts import (
    AppAccessEffect,
    AppAccessPolicy,
    AppAccessDecision,
)

# Continuity
from .continuity_contracts import (
    DIVERGENT_CONTINUITY_MODES,
    ClientDeviceIdentity,
    ContinuityAuditAction,
    ContinuityAuditEvent,
    ContinuityLockSnapshot,
    ContinuityMode,
    LockState,
    OfflineAuthorityGrant,
    OfflineOperationEnvelope,
    OperationEnvelope,
)

# Clinical Visual
from .clinical_visual_contracts import (
    PatientModelVariant,
    AnatomicalView,
    AnatomicalRegion,
    PhysiologicalSystem,
    ClinicalFindingType,
    VisualOverlayType,
    FindingSeverity,
    FindingEvolution,
    ReviewState,
    DetectionMethod,
    ProtocolContext,
    ArcosMode,
    ArcosQualityFlag,
    Laterality,
    CareGraphEvidenceLinkContract,
    StructuredPhysicalFindingContract,
    VasOverlayContract,
    ArcosBodyAnchorContract,
    ArcosOverlayCaptureContract,
    ArcosSessionStartedEvent,
    ArcosAnatomyAnchoredEvent,
    ArcosOverlayCreatedEvent,
    ArcosFindingAcceptedEvent,
    ArcosQualityInsufficientEvent,
)

# Core
from .core_contracts import (
    DomainEvent,
    UserAuthContext,
)

# CrewLink
from .crewlink_contracts import (
    CrewPageSentEvent,
    CrewPageAcknowledgedEvent,
    CrewPageEscalatedEvent,
    CrewMemberContract,
    CrewRosterSyncContract,
)

# ePCR
from .epcr_contracts import (
    EpcrChartAmendedEvent,
    EpcrChartCreatedEvent,
    EpcrBillingCertificationBlock,
    EpcrBillingCrewMember,
    EpcrBillingInsuranceBlock,
    EpcrBillingPatientDemographics,
    EpcrBillingSnapshot,
    EpcrBillingTransportBlock,
    EpcrChartFinalizedEvent,
    EpcrChartHospitalHandoffEvent,
    EpcrNemsisSubmitSucceededEvent,
    EpcrChartContract,
    EpcrPatientProfileContract,
    EpcrVitalSetContract,
    EpcrClinicalImpressionContract,
    EpcrMedicationAdministrationContract,
    EpcrSignatureArtifactContract,
    EpcrNemsissComplianceContract,
)

# ePCR <-> MAR Medication Reconciliation
from .epcr_reconciliation_contracts import (
    EpcrReconciliationStatus,
    EpcrDiscrepancyType,
    EpcrResolutionAction,
    EpcrMedItem,
    EpcrReconciliationCreateRequest,
    EpcrReconciliationResolveRequest,
    EpcrFieldDiff,
    EpcrReconciliationDiscrepancy,
    EpcrReconciliationResponse,
    EpcrReconciliationListResponse,
)

# Feature Flags
from .feature_flag_contracts import (
    FeatureFlagStatus,
    TargetType,
    FeatureFlagRule,
    FeatureFlagContract,
    FeatureFlagResolutionRequest,
    FeatureFlagResolutionResponse,
    FeatureFlagUpdatedEvent,
)

# Field
from .field_contracts import (
    UnitStatusEvent,
    UnitTelemetryEvent,
)

# Inventory
from .inventory_contracts import (
    InventoryItemCreateRequest,
    InventoryItemUpdateRequest,
    InventoryItemResponse,
    InventoryItemListResponse,
    InventoryTransactionCreateRequest,
    InventoryTransactionResponse,
    InventoryTransactionListResponse,
    InventoryBatchTransactionRequest,
    InventoryBatchTransactionResponse,
    InventoryTransferRequest,
    InventoryUsageLineItem,
    InventoryUsageRequest,
    InventoryBarcodeLookupRequest,
    InventoryBarcodeLookupResponse,
    StockLevelReport,
    StockLevelReportResponse,
    ExpiringItemReport,
    ExpiringItemReportResponse,
    InventoryStatsByTypeEntry,
    InventoryMonthlyUsageEntry,
    InventoryStatsResponse,
    InventoryAlertResponse,
    NarcoticDiscrepancyResponse,
    InventoryAlertMetricsResponse,
    InventoryAlertsDashboardResponse,
    InventoryLocationCreateRequest,
    InventoryLocationResponse,
    InventoryLocationListResponse,
    EquipmentAssetCreateRequest,
    EquipmentAssetUpdateRequest,
    EquipmentAssetResponse,
    EquipmentAssetListResponse,
    MaintenanceRecordCreateRequest,
    MaintenanceRecordResponse,
    MaintenanceRecordListResponse,
    SupplierCreateRequest,
    SupplierResponse,
    SupplierListResponse,
    PurchaseOrderItemRequest,
    PurchaseOrderCreateRequest,
    PurchaseOrderUpdateRequest,
    PurchaseOrderResponse,
    PurchaseOrderListResponse,
    PurchaseOrderItemReceived,
    PurchaseOrderReceiveRequest,
    ReceivingVarianceEntry,
    InventoryCycleCountCreateRequest,
    InventoryCycleCountResponse,
    InventoryCycleCountListResponse,
    InventoryCycleCountLineUpsertRequest,
    InventoryCycleCountLineResponse,
    InventoryCycleCountCompleteRequest,
    CycleCountWitnessAffirmRequest,
    AutoDraftPoSummaryEntry,
    AutoDraftPoSummaryResponse,
    IncidentCostLineItem,
    IncidentCostReportResponse,
    InventoryEngineStatusResponse,
    InventoryEngineOverviewResponse,
    InventoryBalanceItemResponse,
    InventoryBalanceSummaryResponse,
    InventoryLocationTreeNodeResponse,
    InventoryLocationMapResponse,
    InventoryReadinessLocationResponse,
    InventoryReadinessResponse,
    InventoryReplayEventResponse,
    InventoryReplayResponse,
    InventoryItemStatus,
    EquipmentAssetStatus,
    PurchaseOrderStatus,
    CycleCountStatus,
    InventorySupplyItemCreatedEvent,
    InventoryStockCountRecordedEvent,
    InventoryReorderThresholdCrossedEvent,
    InventoryStockUsageRecordedEvent,
    InventoryStockTransferCompletedEvent,
    InventoryPurchaseOrderReceivedEvent,
    InventoryCycleCountCompletedEvent,
    InventoryDiscrepancyFlaggedEvent,
)

# Narcotic
from .narcotic import (
    NarcoticVaultType,
    NarcoticVaultStatus,
    ControlledSubstanceSchedule,
    NarcoticMedicationStatus,
    NarcoticTransactionType,
    NarcoticInvestigationStatus,
    NarcoticAccessType,
    CountType,
    ShiftPhase,
    RecallStatus,
    WitnessEventType,
    ComplianceType,
    ActionStatus,
    KitStatus,
    VaultCreateRequest,
    VaultUpdateRequest,
    VaultResponse,
    VaultListResponse,
    MedicationCreateRequest,
    MedicationUpdateRequest,
    MedicationResponse,
    MedicationListResponse,
    IssueNarcoticRequest,
    ReturnNarcoticRequest,
    AdministerNarcoticRequest,
    WasteNarcoticRequest,
    TransferNarcoticRequest,
    TransactionResponse,
    TransactionListResponse,
    ConductAuditRequest,
    AuditResponse,
    AuditListResponse,
    RecordDiscrepancyRequest,
    ResolveDiscrepancyRequest,
    DiscrepancyResponse,
    DiscrepancyListResponse,
    ExpiringMedicationsRequest,
    ExpiringMedicationResponse,
    DEAReportRequest,
    DEAReportResponse,
    AccessLogResponse,
    AccessLogListResponse,
    NarcoticVaultCreatedEvent,
    NarcoticMedicationAddedEvent,
    NarcoticTransactionRecordedEvent,
    NarcoticDiscrepancyRecordedEvent,
)

# Fire
from .fire_contracts import (
    FireIncidentCreatedEvent,
    FireIncidentStatusUpdatedEvent,
    FireIncidentContract,
    FireOperationalEventContract,
    SceneStateSnapshotContract,
    InspectionCaseContract,
    InspectionFindingContract,
    ResourceExecutionContract,
    FirePatientCareLinkContract,
    AfterburnReplayContract,
    NerisReadinessContract,
)

# Metrics
from .metrics_contracts import (
    FORBIDDEN_TELEMETRY_DIMENSION_KEYS,
    MetricSeverity,
    ServiceHealthStatus,
    QueueMetric,
    LatencyMetric,
    ErrorRateMetric,
    ProductTelemetryEvent,
    TelemetryOutcome,
    ThroughputMetric,
    ServiceHealthSummary,
    ServiceHealthReportedEvent,
)

# Billing-vendor migration
from .migration_contracts import (
    MIGRATION_CONTRACT_SCHEMA_VERSION,
    MIGRATION_STATE_TRANSITIONS,
    MIGRATION_TERMINAL_STATES,
    MigrationConfidence,
    MigrationMoneyCents,
    MigrationNonNegativeCents,
    MigrationState,
    MigrationEraState,
    MappingDecisionLevel,
    MigrationExceptionCategory,
    MigrationReconciliationStatus,
    MigrationErrorCode,
    is_legal_migration_transition,
    MigrationSourceFile,
    SourceSchemaFingerprint,
    VendorProfileRef,
    FieldMappingProposal,
    ReconciliationControl,
    ReconciliationRunResult,
    MigrationExceptionGroup,
    CutoverWatermark,
    MigrationSignoff,
    MigrationError,
    MigrationCreated,
    SourceRegistered,
    SourceFileLanded,
    SourceProfiled,
    MappingProposed,
    MappingApproved,
    DryRunCompleted,
    MigrationExceptionRaised,
    ReconciliationCompleted,
    CutoverApproved,
    OpenARActivated,
    MigrationCompleted,
    MigrationRolledBack,
)

# NEMSIS
from .nemsis_exports import (
    ExportLifecycleStatus,
    ExportFailureType,
    ExportTriggerSource,
    ExportReadinessSnapshot,
    ExportArtifactMetadata,
    ExportAttemptSummary,
    ExportAttemptDetail,
    GenerateExportRequest,
    GenerateExportResponse,
    ExportHistoryResponse,
    ExportDetailResponse,
    RetryExportRequest,
    RetryExportResponse,
)

# OCR
from .ocr_contracts import (
    OcrSourceType,
    OcrJobStatus,
    OcrFieldConfidence,
    OcrJobCreate,
    OcrJobStatusResponse,
    OcrJobDetailResponse,
    OcrFieldCandidateResponse,
    OcrFieldApproval,
    OcrApprovalRequest,
    OcrApprovalResponse,
    OcrExtractionCompletedEvent,
    OcrFieldsApprovedEvent,
)

# Patient Portal
from .patient_portal_contracts import (
    PatientVerificationMethod,
    PaymentMethod,
    DisputeReason,
    PatientVerifyRequest,
    PatientVerifyResponse,
    PatientAccountSummary,
    StatementSummaryResponse,
    StatementDetailResponse,
    StatementLineItem,
    PaymentOptionResponse,
    PaymentSubmitRequest,
    PaymentSubmitResponse,
    PaymentPlanRequest,
    PaymentPlanResponse,
    DisputeSubmitRequest,
    DisputeSubmitResponse,
    PatientDocumentResponse,
    CommunicationEventResponse,
    AiExplanationRequest,
    AiExplanationResponse,
    SupportEscalationRequest,
    SupportEscalationResponse,
)

# Search
from .search_contracts import (
    SearchDomain,
    SearchResultType,
    SearchSortOrder,
    SearchQueryRequest,
    SearchResultItem,
    SearchResponse,
    IndexDocumentRequest,
    IndexDocumentResponse,
    DeleteIndexDocumentRequest,
    DeleteIndexDocumentResponse,
    SearchExecutedEvent,
    DocumentIndexedEvent,
    DocumentDeletedEvent,
)

# Transport
from .transport_contracts import (
    TransportRequestTypeContract,
    TransportRequestStatusContract,
    RecurrencePatternContract,
    TransportRequestCreate,
    TransportRequestResponse,
    TripScheduleRequest,
    TripResponse,
    RecurringSeriesCreate,
    RecurringSeriesResponse,
    CalendarEventResponse,
    SlotSuggestionRequest,
    SlotSuggestionResponse,
    DocumentPackageResponse,
    DocumentItemResponse,
    SignatureStatusResponse,
    SignerStatusResponse,
    ReadinessStateResponse,
    ReadinessGate,
    FacilityResponse,
    CadPushRequest,
    CadPushResponse,
    TransportRequestCreatedEvent,
    TripScheduledEvent,
    SignatureCompletedEvent,
    CadPushRequestedEvent,
)

# Voice
from .voice_contracts import (
    VoiceRoomCreatedEvent,
    VoiceRoomClosedEvent,
)

# Workflow
from .workflow_contracts import (
    WorkflowStatus,
    WorkflowStepStatus,
    WorkflowStep,
    WorkflowContext,
    WorkflowExecution,
    WorkflowStartRequest,
    WorkflowStartResponse,
    WorkflowStepCompletedEvent,
    WorkflowFailedEvent,
    WorkflowCompensationTriggeredEvent,
)

# Labor
from .labor_contracts import (
    EmploymentStatus,
    LaborDomain,
    ShiftStatus,
    AssignmentStatus,
    TradeStatus,
    LeaveStatus,
    ClaimStatus as LaborClaimStatus,
    CommandPosture,
    PayrollExportStatus,
    PolicyStatus as LaborPolicyStatus,
    LaborShiftContract,
    LaborAssignmentContract,
    LaborEmployeeReadinessContract,
    LaborShiftPublishedEvent,
    LaborShiftLockedEvent,
    LaborAssignmentCommittedEvent,
    LaborOpenShiftClaimSubmittedEvent,
    LaborShiftTradeProposedEvent,
    LaborLeaveRequestSubmittedEvent,
    LaborComplianceViolationCreatedEvent,
    LaborFatigueRestrictionAppliedEvent,
    LaborPayrollExportSubmittedEvent,
    LaborExternalSyncCompletedEvent,
)

# Graph
from .graph_contracts import (
    GraphEmailSummaryContract,
    GraphEmailDetailContract,
    GraphDriveFileContract,
    GraphCalendarEventContract,
    GraphAvailabilitySlotContract,
    GraphServiceStatusContract,
    GraphSendEmailRequest,
    GraphCreateCalendarEventRequest,
)

# AI
from .ai_contracts import (
    AIRunStatus,
    AIWorkflowType,
    AIRunContract,
    AIRunCreateRequest,
    AIRunResponse,
    BillingCopilotRiskScoreContract,
    BillingCopilotDenialPredictionContract,
    BillingCopilotAppealDraftContract,
    TranscriptSummaryContract,
    AIRunCompletedEvent,
)

# Telnyx
from .telnyx_contracts import (
    TelnyxEventType,
    TelnyxCallDirection,
    TelnyxCallStatus,
    TelnyxCallCompletedEvent,
    TelnyxTranscriptContract,
    TelnyxRecordingContract,
    TelnyxAISummaryContract,
    TelnyxWebhookEventContract,
    TelnyxCallCreatedEvent,
    TelnyxTranscriptionCompletedEvent,
)

# Telephony platform (provider-agnostic Call/Voicemail/Queue/Presence)
from .telephony_contracts import (
    DestinationType,
    CallStatus,
    VoicemailStatus,
    QueueStatus,
    TelephonyEventType,
    Call,
    Voicemail,
    Queue,
    UserPresence,
)

# Workforce
from .workforce_contracts import (
    ShiftStatus as WorkforceShiftStatus,
    AvailabilityType,
    TimeOffStatus,
    FatigueLevel,
    WorkforceShiftContract,
    WorkforceShiftAssignmentContract,
    WorkforceAvailabilityContract,
    WorkforceTimeOffContract,
    WorkforceFatigueEventContract,
    WorkforceReadinessContract,
    WorkforceShiftCreatedEvent,
    WorkforceShiftAssignedEvent,
    WorkforceFatigueAlertEvent,
)

# Medications
from .medications_contracts import (
    MedicationRouteOfAdmin,
    DoseSafetyStatus,
    MedicationCatalogContract,
    MedicationAdministrationContract,
    MedicationProtocolRuleContract,
    DoseSafetyCheckRequest,
    DoseSafetyCheckResponse,
    MedicationExpirationAlertContract,
    UnitMedicationReadinessContract,
    MedicationAdministeredEvent,
    MedicationExpirationWarningEvent,
)

# Tenant
from .tenant_contracts import (
    TenantStatus,
    TenantScopedModel,
    TenantContract,
    TenantCreateRequest,
    TenantUpdateRequest,
    TenantResponse,
    TenantCreatedEvent,
    TenantSuspendedEvent,
)

# Admin
from .admin_contracts import (
    AdminAction,
    UserContract,
    UserCreateRequest,
    UserUpdateRequest,
    RoleContract,
    PermissionContract,
    ApiKeyContract,
    ServiceIdentityContract,
    PaginationContract,
    PaginatedResponse,
)

# Founder
from .founder_contracts import (
    RevenueTimePeriod,
    FounderRevenueMetricContract,
    FounderOperatingExpenseContract,
    FounderRevenueEntryContract,
    FounderFinancialTransactionContract,
    FounderDashboardSummary,
    FounderExportRequest,
    FounderExportResponse,
)

# CRM
from .crm_contracts import (
    RelationshipStage,
    InvestorType,
    CommitmentStatus,
    PartnerType,
    PartnerStatus,
    OpportunityType,
    OpportunityStatus,
    RelationshipCreateRequest,
    RelationshipResponse,
    RelationshipListResponse,
    RelationshipStageTransitionRequest,
    InvestorCreateRequest,
    InvestorResponse,
    InvestorRoundCreateRequest,
    InvestorRoundResponse,
    InvestorCommitmentCreateRequest,
    InvestorCommitmentResponse,
    InvestorRoundSummaryResponse,
    PartnerCreateRequest,
    PartnerResponse,
    PartnerAgreementCreateRequest,
    PartnerAgreementResponse,
    PartnerPerformanceCreateRequest,
    PartnerPerformanceResponse,
    PartnerDashboardResponse,
    GrowthMetricCreateRequest,
    GrowthMetricResponse,
    GrowthDashboardResponse,
    GrowthTrendResponse,
    GrowthForecastRequest,
    GrowthForecastResponse,
    FounderOpportunityCreateRequest,
    FounderOpportunityUpdateRequest,
    FounderOpportunityResponse,
    FounderOpportunityListResponse,
)

# Finance
from .finance_contracts import (
    AccountType,
    TransactionSource,
    ReconciliationStatus,
    FinancialSummaryStatus,
    FinancialSummaryCreateRequest,
    FinancialSummaryUpdateRequest,
    FinancialSummaryResponse,
    FinancialSummaryListResponse,
    RevenueRecordCreateRequest,
    RevenueRecordResponse,
    RevenueRecordListResponse,
    LedgerAccountCreateRequest,
    LedgerAccountUpdateRequest,
    LedgerAccountResponse,
    LedgerAccountListResponse,
    JournalLineRequest,
    JournalEntryCreateRequest,
    JournalLineResponse,
    JournalEntryResponse,
    JournalEntryListResponse,
    ReconciliationPeriodResponse,
    FinanceDashboardSummaryResponse,
    RevenueRecordCreatedEvent,
    JournalEntryPostedEvent,
)

# Dispatch
from .dispatch_contracts import (
    DispatchStatus,
    DispatchPriority,
    DispatchGpsCoordinate,
    DispatchContract,
    DispatchStatusUpdateEvent,
    DispatchCreatedEvent,
    DispatchClosedEvent,
    DispatchUnitGpsPingEvent,
)

# Platform Events
from .platform_event_contracts import (
    AdaptixEventType,
    AdaptixPlatformEvent,
    PulseMessageType,
    PulseMessage,
)


# Explicit public surface
# ---------------------------------------------------------------------------
# Shared platform primitives (Wave 0)
# ---------------------------------------------------------------------------
# Cross-cutting contracts every domain depends on, deliberately owned here
# rather than duplicated per module. Helper predicates (is_decided, is_terminal,
# requires_reconciliation, is_open, has_state_conflict, ...) stay importable from
# their own modules rather than joining this root surface, whose names are
# re-exported at ``adaptix_contracts`` package level.

# Human confirmation (primitive B)
from .human_confirmation_contracts import (
    DECIDED_DISPOSITIONS,
    HumanConfirmationReceipt,
    HumanDisposition,
)

# Rule packs (primitive C)
from .rule_pack_contracts import (
    MUTABLE_RULE_PACK_STATES,
    RulePack,
    RulePackRule,
    RulePackState,
)

# Provider adapters (primitive D)
from .provider_adapter_contracts import (
    RECONCILIATION_PROVIDER_STATES,
    TERMINAL_PROVIDER_STATES,
    ProviderOperationRecord,
    ProviderOperationState,
    ProviderRetryability,
    ProviderTransportResult,
)

# Exception inbox (primitive F)
from .exception_contracts import (
    TERMINAL_EXCEPTION_STATUSES,
    ExceptionRecord,
    ExceptionSeverity,
    ExceptionStatus,
)

# Protected-state conflicts (primitive G)
from .state_conflict_contracts import (
    ProtectedStateKind,
    ProtectedStateWrite,
    StateConflict,
)

# Outcome attribution (primitive K)
from .outcome_attribution_contracts import (
    CAUSAL_ATTRIBUTION_METHODS,
    AttributionMethod,
    OutcomeAttribution,
    OutcomeDefinition,
    OutcomeDirection,
    OutcomeObservation,
)


__all__ = [
    # Concept Intelligence — terminology + graph concept contracts (Phase 2)
    "ConceptType",
    "ConceptStatus",
    "TermType",
    "MappingType",
    "MappingDirection",
    "ReleaseStatus",
    "ReviewStatus",
    "LicenseStatus",
    "AssertionStatus",
    "Temporality",
    "Experiencer",
    "Certainty",
    "MatchReason",
    "CrosswalkClassification",
    "TerminologyEventType",
    "TerminologySource",
    "SourceRelease",
    "Concept",
    "ConceptTerm",
    "SemanticType",
    "TerminologyCode",
    "CodeMapping",
    "EvidenceSpan",
    "AssertionContext",
    "ConfidenceBreakdown",
    "ConceptCandidate",
    "ConceptResolutionRequest",
    "ConceptResolutionResponse",
    "AutocodeMappingCandidate",
    "AutocodeConcept",
    "AutocodeOutput",
    "GraphConceptNode",
    "GraphRelationshipProvenance",
    "GraphRelationship",
    "GraphRelationshipExplanation",
    "TerminologyEventEnvelope",
    # Concept Intelligence — terminology concept event contracts (SignalCore-based)
    "TerminologyConceptEventType",
    "TerminologyConceptEventPayload",
    "build_terminology_event",
    "validate_terminology_event",
    # Event infrastructure contracts
    "EventSchema",
    "EventMetadata",
    "EventValidator",
    "LocalEventConsumerRegistry",
    # Air
    "AirMissionCreatedEvent",
    "AirMissionStatusUpdatedEvent",
    "AirMissionContract",
    "AirLandingZoneContract",
    # Calendar kernel
    "AdaptixCalendarAuditAction",
    "AdaptixCalendarAuditEvent",
    "AdaptixCalendarConflict",
    "AdaptixCalendarConflictReason",
    "AdaptixCalendarEvent",
    "AdaptixCalendarEventStatus",
    "AdaptixCalendarProduct",
    "AdaptixCalendarResource",
    "AdaptixCalendarResourceKind",
    "CalendarAvailabilityResponse",
    "CalendarAuditEntry",
    "CalendarEventCreateRequest",
    "CalendarEventUpdateRequest",
    # Air Pilot
    "PilotGoNoGoEvent",
    "PilotReadinessStatus",
    # Audit
    "AuditActorType",
    "AuditActionType",
    "AuditSeverity",
    "ComplianceReviewStatus",
    "AuditContext",
    "AuditRecord",
    "PhiAccessRecord",
    "SecurityEventRecord",
    "ComplianceReviewItem",
    "AuditRecordCreatedEvent",
    "PhiAccessLoggedEvent",
    "SecurityEventDetectedEvent",
    "ComplianceReviewOpenedEvent",
    # Duty Auth
    "FieldLoginRequest",
    "FieldLoginResolved",
    "CreateDutySessionRequest",
    "DutySessionResponse",
    "EndDutySessionRequest",
    "EndDutySessionResponse",
    "RevokeBadgeRequest",
    "RevokeBadgeResponse",
    "AuthAuditEvent",
    # Billing
    "ClaimStatus",
    "DenialStatus",
    "PaymentStatus",
    "ClearinghouseStatus",
    "LiveBillingClearinghouse",
    "ClearinghouseProvider",
    "MigrationSourceVendor",
    "PayerType",
    "ClaimLineItem",
    "AdjustmentContract",
    "PayerContract",
    "ClaimContract",
    "DenialContract",
    "PaymentContract",
    "RemittanceContract",
    "ClearinghouseSubmission",
    "ClaimCreatedEvent",
    "ClaimSubmittedEvent",
    "ClaimStatusUpdatedEvent",
    "DenialCreatedEvent",
    "PaymentPostedEvent",
    "RemittanceReceivedEvent",
    "ClearinghouseAckReceivedEvent",
    # Billing Auth
    "BillingRole",
    "BillingPostAuthRoute",
    "MFARequirement",
    "SessionAnomalyState",
    "BillingSignInContext",
    "BillingAccessResolution",
    "BillingOrgSelectorEntry",
    # Billing Clearinghouse
    "SubmissionStatus",
    "AckType",
    "StediReadinessState",
    "StediWebhookVerification",
    "StediReadinessBlockerOwner",
    "StediMigrationMode",
    "StediMigrationTransitionKind",
    "StediEnrollmentTransactionType",
    "StediPayerEnrollmentStatus",
    "SubmissionAttemptStatus",
    "RemittancePostingStatus",
    "SubmissionFrequency",
    "StediArtifactTransactionKind",
    "StediClaimTransition",
    "StediWebhookProcessingStatus",
    "StediProviderRow",
    "StediPayerRow",
    "StediWebhookStatus",
    "StediStatusBlocker",
    "StediStatusResponse",
    "StediAllowedTransition",
    "StediMigrationModeResponse",
    "StediMigrationTransitionRequest",
    "StediMigrationTransitionResponse",
    "StediMigrationTransitionHistoryRow",
    "StediCreateEnrollmentRequest",
    "StediCreateEnrollmentResponse",
    "MigrationSourceClearinghouseSettingsResponse",
    "MigrationSourceClearinghouseSettingsUpdate",
    "SubmissionSummaryResponse",
    "RemittanceSummary",
    "RemittanceListResponse",
    "StediServiceLineOutcome",
    "StediNormalizedArtifact",
    "StediNormalizationResult",
    "StediWebhookReconcileOutcome",
    "ClaimSubmissionRequest",
    "ClaimSubmissionResponse",
    "ClearinghouseAck",
    "ClaimAckStatus",
    "RemittanceIngestRequest",
    "RemittanceClaimPayment",
    "RemittanceIngestResponse",
    "ClaimSubmittedToClearinghouseEvent",
    "RemittanceIngestedEvent",
    # Billing Clearinghouse — Stedi inbound webhook (PR #541)
    "StediWebhookEventType",
    "StediWebhookRequest",
    "StediWebhookAcceptedResponse",
    "StediWebhookDuplicateResponse",
    "StediWebhookRejectedResponse",
    # Billing Clearinghouse — retry-eligibility + operator fallback (PR #539)
    "ClaimTransmissionState",
    "ClaimRetryReasonCode",
    "ClaimRetryEligibilityResponse",
    "ClaimOperatorFallbackRequest",
    "ClaimOperatorFallbackResponse",
    "OperatorFallbackRefusedReasonCode",
    "ClaimOperatorFallbackRefusedError",
    "ClaimOperatorFallbackTargetFailedError",
    # Billing Eligibility
    "EligibilityStatus",
    "CoverageLevel",
    "AuthorizationStatus",
    "EligibilityRequest",
    "EligibilityBenefitSummary",
    "EligibilityResponse",
    "EligibilityCheckedEvent",
    "AuthorizationStatusUpdatedEvent",
    # Billing Portal
    "SurfaceAvailability",
    "UrgencyLevel",
    "BillingPriorityQueueSummary",
    "BillingBlockedClaimsSummary",
    "BillingDenialQueueSummary",
    "BillingAgedARSummary",
    "BillingUnderpaymentSummary",
    "BillingPatientFinancialSummary",
    "BillingIntegrationHealthSummary",
    "BillingOperatorSummary",
    "BillingPortalHomeSummary",
    "ClaimDefectSeverity",
    "ClaimDefect",
    "ClaimReadinessSummary",
    "ClaimIntakeRecord",
    "SubmissionAttempt",
    "SubmissionTimelineEvent",
    "DenialRecord",
    "DenialCluster",
    "DenialRootCauseSummary",
    "DenialRecoveryForecast",
    "FounderTenantFinancialSummary",
    "FounderBillingOverview",
    # Billing Transport
    "TransportReadinessRequest",
    "TransportReadinessResponse",
    "BillingReadinessGate",
    "TransportReadinessGateStatus",
    "ClaimArtifactAttachRequest",
    "ClaimArtifactAttachResponse",
    "BillingTransportLinkEvent",
    "ClaimReadinessResolvedEvent",
    # CAD
    "CadCaseCreatedEvent",
    "CadCaseStatusUpdatedEvent",
    "CadCaseContract",
    "CadUnitAssignedEvent",
    # CAD Transport
    "CadTransportLaneStatus",
    "CadTransportLinkStatus",
    "CadTransportLinkContract",
    "CadDispatchReadyEntryContract",
    "CadTransportExceptionEntryContract",
    "CadTransportStatusSyncContract",
    "ScheduledTransportLaneItem",
    "DispatchReadyItem",
    "CadTransportException",
    "CadTransportActivateRequest",
    "CadTransportActivateResponse",
    "CadTransportSyncPayload",
    "CadTransportSyncResponse",
    "TransportActivatedEvent",
    "TransportStatusSyncedEvent",
    # Communications
    "NotificationRequest",
    "NotificationDeliveredEvent",
    "NotificationFailedEvent",
    # Contract onboarding
    "ContractLifecycleStatus",
    "ContractServiceScope",
    "ContractPayerMix",
    "ContractPricingTerms",
    "ContractBillingRules",
    "ContractModuleTerms",
    "ContractIntakeRequest",
    "ContractRecord",
    "TrustSignExecutionRequest",
    "TrustSignExecutionResponse",
    "TrustSignCallbackEvent",
    "DropboxSignExecutionRequest",
    "DropboxSignExecutionResponse",
    "DropboxSignCallbackEvent",
    "ContractActivationRequest",
    "ContractActivationResponse",
    "ContractStatusChangedEvent",
    # Signup application creation
    "SIGNUP_IDEMPOTENCY_HEADER",
    "SignupAgencyAddress",
    "SignupApplicationCreateRequest",
    "SignupApplicationCreateResponse",
    "SignupIdempotencyKey",
    # Legal execution
    "ContractType",
    "ContractStatus",
    "TenantContractStatusMap",
    "ContractSignatureEvent",
    "ContractAccessCheckRequest",
    "ContractAccessCheckResponse",
    # Continuity
    "ClientDeviceIdentity",
    "ContinuityAuditAction",
    "ContinuityAuditEvent",
    "ContinuityLockSnapshot",
    "LockState",
    "OperationEnvelope",
    # Clinical Visual
    "PatientModelVariant",
    "AnatomicalView",
    "AnatomicalRegion",
    "PhysiologicalSystem",
    "ClinicalFindingType",
    "VisualOverlayType",
    "FindingSeverity",
    "FindingEvolution",
    "ReviewState",
    "DetectionMethod",
    "ProtocolContext",
    "ArcosMode",
    "ArcosQualityFlag",
    "Laterality",
    "CareGraphEvidenceLinkContract",
    "StructuredPhysicalFindingContract",
    "VasOverlayContract",
    "ArcosBodyAnchorContract",
    "ArcosOverlayCaptureContract",
    "ArcosSessionStartedEvent",
    "ArcosAnatomyAnchoredEvent",
    "ArcosOverlayCreatedEvent",
    "ArcosFindingAcceptedEvent",
    "ArcosQualityInsufficientEvent",
    # Core
    "DomainEvent",
    "UserAuthContext",
    # CrewLink
    "CrewPageSentEvent",
    "CrewPageAcknowledgedEvent",
    "CrewPageEscalatedEvent",
    "CrewMemberContract",
    "CrewRosterSyncContract",
    # ePCR
    "EpcrChartAmendedEvent",
    "EpcrChartCreatedEvent",
    "EpcrBillingCertificationBlock",
    "EpcrBillingCrewMember",
    "EpcrBillingInsuranceBlock",
    "EpcrBillingTransportBlock",
    "EpcrBillingPatientDemographics",
    "EpcrBillingSnapshot",
    "EpcrChartFinalizedEvent",
    "EpcrChartHospitalHandoffEvent",
    "EpcrNemsisSubmitSucceededEvent",
    "EpcrChartContract",
    "EpcrPatientProfileContract",
    "EpcrVitalSetContract",
    "EpcrClinicalImpressionContract",
    "EpcrMedicationAdministrationContract",
    "EpcrSignatureArtifactContract",
    "EpcrNemsissComplianceContract",
    # ePCR <-> MAR Medication Reconciliation
    "EpcrReconciliationStatus",
    "EpcrDiscrepancyType",
    "EpcrResolutionAction",
    "EpcrMedItem",
    "EpcrReconciliationCreateRequest",
    "EpcrReconciliationResolveRequest",
    "EpcrFieldDiff",
    "EpcrReconciliationDiscrepancy",
    "EpcrReconciliationResponse",
    "EpcrReconciliationListResponse",
    # Feature Flags
    "FeatureFlagStatus",
    "TargetType",
    "FeatureFlagRule",
    "FeatureFlagContract",
    "FeatureFlagResolutionRequest",
    "FeatureFlagResolutionResponse",
    "FeatureFlagUpdatedEvent",
    # Field
    "UnitStatusEvent",
    "UnitTelemetryEvent",
    # Inventory
    "InventoryItemCreateRequest",
    "InventoryItemUpdateRequest",
    "InventoryItemResponse",
    "InventoryItemListResponse",
    "InventoryTransactionCreateRequest",
    "InventoryTransactionResponse",
    "InventoryTransactionListResponse",
    "InventoryBatchTransactionRequest",
    "InventoryBatchTransactionResponse",
    "InventoryTransferRequest",
    "InventoryUsageLineItem",
    "InventoryUsageRequest",
    "InventoryBarcodeLookupRequest",
    "InventoryBarcodeLookupResponse",
    "StockLevelReport",
    "StockLevelReportResponse",
    "ExpiringItemReport",
    "ExpiringItemReportResponse",
    "InventoryStatsByTypeEntry",
    "InventoryMonthlyUsageEntry",
    "InventoryStatsResponse",
    "InventoryAlertResponse",
    "NarcoticDiscrepancyResponse",
    "InventoryAlertMetricsResponse",
    "InventoryAlertsDashboardResponse",
    "InventoryLocationCreateRequest",
    "InventoryLocationResponse",
    "InventoryLocationListResponse",
    "EquipmentAssetCreateRequest",
    "EquipmentAssetUpdateRequest",
    "EquipmentAssetResponse",
    "EquipmentAssetListResponse",
    "MaintenanceRecordCreateRequest",
    "MaintenanceRecordResponse",
    "MaintenanceRecordListResponse",
    "SupplierCreateRequest",
    "SupplierResponse",
    "SupplierListResponse",
    "PurchaseOrderItemRequest",
    "PurchaseOrderCreateRequest",
    "PurchaseOrderUpdateRequest",
    "PurchaseOrderResponse",
    "PurchaseOrderListResponse",
    "PurchaseOrderItemReceived",
    "PurchaseOrderReceiveRequest",
    "ReceivingVarianceEntry",
    "InventoryCycleCountCreateRequest",
    "InventoryCycleCountResponse",
    "InventoryCycleCountListResponse",
    "InventoryCycleCountLineUpsertRequest",
    "InventoryCycleCountLineResponse",
    "InventoryCycleCountCompleteRequest",
    "CycleCountWitnessAffirmRequest",
    "AutoDraftPoSummaryEntry",
    "AutoDraftPoSummaryResponse",
    "IncidentCostLineItem",
    "IncidentCostReportResponse",
    "InventoryEngineStatusResponse",
    "InventoryEngineOverviewResponse",
    "InventoryBalanceItemResponse",
    "InventoryBalanceSummaryResponse",
    "InventoryLocationTreeNodeResponse",
    "InventoryLocationMapResponse",
    "InventoryReadinessLocationResponse",
    "InventoryReadinessResponse",
    "InventoryReplayEventResponse",
    "InventoryReplayResponse",
    # Narcotic
    "NarcoticVaultType",
    "NarcoticVaultStatus",
    "ControlledSubstanceSchedule",
    "NarcoticMedicationStatus",
    "NarcoticTransactionType",
    "NarcoticInvestigationStatus",
    "NarcoticAccessType",
    "CountType",
    "ShiftPhase",
    "RecallStatus",
    "WitnessEventType",
    "ComplianceType",
    "ActionStatus",
    "KitStatus",
    "VaultCreateRequest",
    "VaultUpdateRequest",
    "VaultResponse",
    "VaultListResponse",
    "MedicationCreateRequest",
    "MedicationUpdateRequest",
    "MedicationResponse",
    "MedicationListResponse",
    "IssueNarcoticRequest",
    "ReturnNarcoticRequest",
    "AdministerNarcoticRequest",
    "WasteNarcoticRequest",
    "TransferNarcoticRequest",
    "TransactionResponse",
    "TransactionListResponse",
    "ConductAuditRequest",
    "AuditResponse",
    "AuditListResponse",
    "RecordDiscrepancyRequest",
    "ResolveDiscrepancyRequest",
    "DiscrepancyResponse",
    "DiscrepancyListResponse",
    "ExpiringMedicationsRequest",
    "ExpiringMedicationResponse",
    "DEAReportRequest",
    "DEAReportResponse",
    "AccessLogResponse",
    "AccessLogListResponse",
    "NarcoticVaultCreatedEvent",
    "NarcoticMedicationAddedEvent",
    "NarcoticTransactionRecordedEvent",
    "NarcoticDiscrepancyRecordedEvent",
    # Fire
    "FireIncidentCreatedEvent",
    "FireIncidentStatusUpdatedEvent",
    "FireIncidentContract",
    "FireOperationalEventContract",
    "SceneStateSnapshotContract",
    "InspectionCaseContract",
    "InspectionFindingContract",
    "ResourceExecutionContract",
    "FirePatientCareLinkContract",
    "AfterburnReplayContract",
    "NerisReadinessContract",
    # Metrics
    "MetricSeverity",
    "ServiceHealthStatus",
    "QueueMetric",
    "LatencyMetric",
    "ErrorRateMetric",
    "ThroughputMetric",
    "ServiceHealthSummary",
    "ServiceHealthReportedEvent",
    # Billing-vendor migration
    "MIGRATION_CONTRACT_SCHEMA_VERSION",
    "MIGRATION_STATE_TRANSITIONS",
    "MIGRATION_TERMINAL_STATES",
    "MigrationConfidence",
    "MigrationMoneyCents",
    "MigrationNonNegativeCents",
    "MigrationState",
    "MigrationEraState",
    "MappingDecisionLevel",
    "MigrationExceptionCategory",
    "MigrationReconciliationStatus",
    "MigrationErrorCode",
    "is_legal_migration_transition",
    "MigrationSourceFile",
    "SourceSchemaFingerprint",
    "VendorProfileRef",
    "FieldMappingProposal",
    "ReconciliationControl",
    "ReconciliationRunResult",
    "MigrationExceptionGroup",
    "CutoverWatermark",
    "MigrationSignoff",
    "MigrationError",
    "MigrationCreated",
    "SourceRegistered",
    "SourceFileLanded",
    "SourceProfiled",
    "MappingProposed",
    "MappingApproved",
    "DryRunCompleted",
    "MigrationExceptionRaised",
    "ReconciliationCompleted",
    "CutoverApproved",
    "OpenARActivated",
    "MigrationCompleted",
    "MigrationRolledBack",
    # NEMSIS
    "ExportLifecycleStatus",
    "ExportFailureType",
    "ExportTriggerSource",
    "ExportReadinessSnapshot",
    "ExportArtifactMetadata",
    "ExportAttemptSummary",
    "ExportAttemptDetail",
    "GenerateExportRequest",
    "GenerateExportResponse",
    "ExportHistoryResponse",
    "ExportDetailResponse",
    "RetryExportRequest",
    "RetryExportResponse",
    # OCR
    "OcrSourceType",
    "OcrJobStatus",
    "OcrFieldConfidence",
    "OcrJobCreate",
    "OcrJobStatusResponse",
    "OcrJobDetailResponse",
    "OcrFieldCandidateResponse",
    "OcrFieldApproval",
    "OcrApprovalRequest",
    "OcrApprovalResponse",
    "OcrExtractionCompletedEvent",
    "OcrFieldsApprovedEvent",
    # Patient Portal
    "PatientVerificationMethod",
    "PaymentMethod",
    "DisputeReason",
    "PatientVerifyRequest",
    "PatientVerifyResponse",
    "PatientAccountSummary",
    "StatementSummaryResponse",
    "StatementDetailResponse",
    "StatementLineItem",
    "PaymentOptionResponse",
    "PaymentSubmitRequest",
    "PaymentSubmitResponse",
    "PaymentPlanRequest",
    "PaymentPlanResponse",
    "DisputeSubmitRequest",
    "DisputeSubmitResponse",
    "PatientDocumentResponse",
    "CommunicationEventResponse",
    "AiExplanationRequest",
    "AiExplanationResponse",
    "SupportEscalationRequest",
    "SupportEscalationResponse",
    # Search
    "SearchDomain",
    "SearchResultType",
    "SearchSortOrder",
    "SearchQueryRequest",
    "SearchResultItem",
    "SearchResponse",
    "IndexDocumentRequest",
    "IndexDocumentResponse",
    "DeleteIndexDocumentRequest",
    "DeleteIndexDocumentResponse",
    "SearchExecutedEvent",
    "DocumentIndexedEvent",
    "DocumentDeletedEvent",
    # Transport
    "TransportRequestTypeContract",
    "TransportRequestStatusContract",
    "RecurrencePatternContract",
    "TransportRequestCreate",
    "TransportRequestResponse",
    "TripScheduleRequest",
    "TripResponse",
    "RecurringSeriesCreate",
    "RecurringSeriesResponse",
    "CalendarEventResponse",
    "SlotSuggestionRequest",
    "SlotSuggestionResponse",
    "DocumentPackageResponse",
    "DocumentItemResponse",
    "SignatureStatusResponse",
    "SignerStatusResponse",
    "ReadinessStateResponse",
    "ReadinessGate",
    "FacilityResponse",
    "CadPushRequest",
    "CadPushResponse",
    "TransportRequestCreatedEvent",
    "TripScheduledEvent",
    "SignatureCompletedEvent",
    "CadPushRequestedEvent",
    # Voice
    "VoiceRoomCreatedEvent",
    "VoiceRoomClosedEvent",
    # Workflow
    "WorkflowStatus",
    "WorkflowStepStatus",
    "WorkflowStep",
    "WorkflowContext",
    "WorkflowExecution",
    "WorkflowStartRequest",
    "WorkflowStartResponse",
    "WorkflowStepCompletedEvent",
    "WorkflowFailedEvent",
    "WorkflowCompensationTriggeredEvent",
    # Labor
    "EmploymentStatus",
    "LaborDomain",
    "ShiftStatus",
    "AssignmentStatus",
    "TradeStatus",
    "LeaveStatus",
    "LaborClaimStatus",
    "CommandPosture",
    "PayrollExportStatus",
    "LaborPolicyStatus",
    "LaborShiftContract",
    "LaborAssignmentContract",
    "LaborEmployeeReadinessContract",
    "LaborShiftPublishedEvent",
    "LaborShiftLockedEvent",
    "LaborAssignmentCommittedEvent",
    "LaborOpenShiftClaimSubmittedEvent",
    "LaborShiftTradeProposedEvent",
    "LaborLeaveRequestSubmittedEvent",
    "LaborComplianceViolationCreatedEvent",
    "LaborFatigueRestrictionAppliedEvent",
    "LaborPayrollExportSubmittedEvent",
    "LaborExternalSyncCompletedEvent",
    # Graph
    "GraphEmailSummaryContract",
    "GraphEmailDetailContract",
    "GraphDriveFileContract",
    "GraphCalendarEventContract",
    "GraphAvailabilitySlotContract",
    "GraphServiceStatusContract",
    "GraphSendEmailRequest",
    "GraphCreateCalendarEventRequest",
    # Inventory domain events
    "InventoryItemStatus",
    "EquipmentAssetStatus",
    "PurchaseOrderStatus",
    "CycleCountStatus",
    "InventorySupplyItemCreatedEvent",
    "InventoryStockCountRecordedEvent",
    "InventoryReorderThresholdCrossedEvent",
    "InventoryStockUsageRecordedEvent",
    "InventoryStockTransferCompletedEvent",
    "InventoryPurchaseOrderReceivedEvent",
    "InventoryCycleCountCompletedEvent",
    "InventoryDiscrepancyFlaggedEvent",
    # AI
    "AIRunStatus",
    "AIWorkflowType",
    "AIRunContract",
    "AIRunCreateRequest",
    "AIRunResponse",
    "BillingCopilotRiskScoreContract",
    "BillingCopilotDenialPredictionContract",
    "BillingCopilotAppealDraftContract",
    "TranscriptSummaryContract",
    "AIRunCompletedEvent",
    # Telnyx
    "TelnyxEventType",
    "TelnyxCallDirection",
    "TelnyxCallStatus",
    "TelnyxCallCompletedEvent",
    "TelnyxTranscriptContract",
    "TelnyxRecordingContract",
    "TelnyxAISummaryContract",
    "TelnyxWebhookEventContract",
    "TelnyxCallCreatedEvent",
    "TelnyxTranscriptionCompletedEvent",
    # Telephony platform
    "DestinationType",
    "CallStatus",
    "VoicemailStatus",
    "QueueStatus",
    "TelephonyEventType",
    "Call",
    "Voicemail",
    "Queue",
    "UserPresence",
    # Workforce
    "WorkforceShiftStatus",
    "AvailabilityType",
    "TimeOffStatus",
    "FatigueLevel",
    "WorkforceShiftContract",
    "WorkforceShiftAssignmentContract",
    "WorkforceAvailabilityContract",
    "WorkforceTimeOffContract",
    "WorkforceFatigueEventContract",
    "WorkforceReadinessContract",
    "WorkforceShiftCreatedEvent",
    "WorkforceShiftAssignedEvent",
    "WorkforceFatigueAlertEvent",
    # Medications
    "MedicationRouteOfAdmin",
    "DoseSafetyStatus",
    "MedicationCatalogContract",
    "MedicationAdministrationContract",
    "MedicationProtocolRuleContract",
    "DoseSafetyCheckRequest",
    "DoseSafetyCheckResponse",
    "MedicationExpirationAlertContract",
    "UnitMedicationReadinessContract",
    "MedicationAdministeredEvent",
    "MedicationExpirationWarningEvent",
    # Tenant
    "TenantStatus",
    "TenantScopedModel",
    "TenantContract",
    "TenantCreateRequest",
    "TenantUpdateRequest",
    "TenantResponse",
    "TenantCreatedEvent",
    "TenantSuspendedEvent",
    # Admin
    "AdminAction",
    "UserContract",
    "UserCreateRequest",
    "UserUpdateRequest",
    "RoleContract",
    "PermissionContract",
    "ApiKeyContract",
    "ServiceIdentityContract",
    "PaginationContract",
    "PaginatedResponse",
    # Founder
    "RevenueTimePeriod",
    "FounderRevenueMetricContract",
    "FounderOperatingExpenseContract",
    "FounderRevenueEntryContract",
    "FounderFinancialTransactionContract",
    "FounderDashboardSummary",
    "FounderExportRequest",
    "FounderExportResponse",
    # CRM
    "RelationshipStage",
    "InvestorType",
    "CommitmentStatus",
    "PartnerType",
    "PartnerStatus",
    "OpportunityType",
    "OpportunityStatus",
    "RelationshipCreateRequest",
    "RelationshipResponse",
    "RelationshipListResponse",
    "RelationshipStageTransitionRequest",
    "InvestorCreateRequest",
    "InvestorResponse",
    "InvestorRoundCreateRequest",
    "InvestorRoundResponse",
    "InvestorCommitmentCreateRequest",
    "InvestorCommitmentResponse",
    "InvestorRoundSummaryResponse",
    "PartnerCreateRequest",
    "PartnerResponse",
    "PartnerAgreementCreateRequest",
    "PartnerAgreementResponse",
    "PartnerPerformanceCreateRequest",
    "PartnerPerformanceResponse",
    "PartnerDashboardResponse",
    "GrowthMetricCreateRequest",
    "GrowthMetricResponse",
    "GrowthDashboardResponse",
    "GrowthTrendResponse",
    "GrowthForecastRequest",
    "GrowthForecastResponse",
    "FounderOpportunityCreateRequest",
    "FounderOpportunityUpdateRequest",
    "FounderOpportunityResponse",
    "FounderOpportunityListResponse",
    # Finance
    "AccountType",
    "TransactionSource",
    "ReconciliationStatus",
    "FinancialSummaryStatus",
    "FinancialSummaryCreateRequest",
    "FinancialSummaryUpdateRequest",
    "FinancialSummaryResponse",
    "FinancialSummaryListResponse",
    "RevenueRecordCreateRequest",
    "RevenueRecordResponse",
    "RevenueRecordListResponse",
    "LedgerAccountCreateRequest",
    "LedgerAccountUpdateRequest",
    "LedgerAccountResponse",
    "LedgerAccountListResponse",
    "JournalLineRequest",
    "JournalEntryCreateRequest",
    "JournalLineResponse",
    "JournalEntryResponse",
    "JournalEntryListResponse",
    "ReconciliationPeriodResponse",
    "FinanceDashboardSummaryResponse",
    "RevenueRecordCreatedEvent",
    "JournalEntryPostedEvent",
    # Dispatch
    "DispatchStatus",
    "DispatchPriority",
    "DispatchGpsCoordinate",
    "DispatchContract",
    "DispatchStatusUpdateEvent",
    "DispatchCreatedEvent",
    "DispatchClosedEvent",
    "DispatchUnitGpsPingEvent",
    # Platform Events
    "AdaptixEventType",
    "AdaptixPlatformEvent",
    "PulseMessageType",
    "PulseMessage",
    # Audit (extended domain actions)
    "AuditDomainAction",
    "AuditEntry",
    # Cortex (separated service)
    "RecommendationRequest",
    "RecommendationResponse",
    # TrustSign (separated service)
    "SignaturePackageCreateRequest",
    "SignaturePackageResponse",
    # SageMaker (separated service)
    "PredictionRequest",
    "PredictionResponse",
    # Gateway (separated service)
    "GatewayRouteRegistryEntry",
    "ForwardedRequestContext",
    # Audit (shared service)
    "AuditExportFormat",
    "AuditEvent",
    "AuditSearchQuery",
    "AuditExportRequest",
    "AuditIngestRequest",
    "AuditIngestResponse",
    "AuditSearchResponse",
    "AuditExportStatus",
    "AuditExportResponse",
    # Notification (shared service)
    "NotificationChannel",
    "NotificationStatus",
    "NotificationDeliveryStatus",
    "NotificationPreference",
    "NotificationTemplate",
    "NotificationSendRequest",
    "NotificationPreferenceSet",
    "NotificationQueuedEvent",
    "NotificationSentEvent",
    "NotificationReadEvent",
    # Facility (shared service)
    "FacilityType",
    "FacilityStatus",
    "FacilityContact",
    "FacilityAlias",
    "FacilityMapping",
    "FacilityCapability",
    "FacilityRecord",
    "FacilitySearchRequest",
    "FacilitySearchResponse",
    "FacilityCreateRequest",
    "FacilityUpdateRequest",
    "FacilityAliasCreateRequest",
    "FacilityMappingUpsertRequest",
    "CmsNpiSyncRequest",
    "CmsNpiSyncResult",
    "FacilityRegisteredEvent",
    "FacilityUpdatedEvent",
    "FacilityMergedEvent",
    # Geo (shared service)
    "GeoCoordinate",
    "GeocodeRequest",
    "GeocodeResult",
    "DistanceResult",
    "RouteEstimate",
    "ServiceArea",
    "ReverseGeocodeRequest",
    "AutocompleteRequest",
    "AddressSuggestion",
    "AutocompleteResult",
    "RouteRequest",
    "DistanceRequest",
    "GeoClient",
    # SignalCore (shared service)
    "EventDeliveryStatus",
    "SignalCoreEvent",
    "SignalCoreTrigger",
    # Forms (shared service)
    "FormFieldType",
    "FormStatus",
    "FormValidationRule",
    "FormFieldDefinition",
    "FormSchema",
    "FormVersion",
    "FormTemplate",
    "FormValidationError",
    "FormSubmission",
    "FormTemplateCreateRequest",
    "FormTemplateUpdateRequest",
    "FormVersionCreateRequest",
    "FormSubmissionCreateRequest",
    "FormTemplateListResponse",
    "FormSubmissionListResponse",
    "FormPublishedEvent",
    "FormSubmittedEvent",
    # Reference Data (shared service)
    "ReferenceDataItem",
    "ReferenceDataList",
    "ReferenceDataPayerType",
    "ServiceLevel",
    "StateCode",
    "ReferenceDataListCreateRequest",
    "ReferenceDataListUpdateRequest",
    "ReferenceDataItemUpsertRequest",
    "ReferenceDataQuery",
    "ReferenceDataListResponse",
    "ReferenceDataPublishRequest",
    "ReferenceDataPublishResponse",
    "ReferenceDataListPublishedEvent",
    "ReferenceDataListUpdatedEvent",
    # Payment (shared service — Stripe subscriptions)
    "SubscriptionStatus",
    "InvoiceStatus",
    "PaymentEventType",
    "StripeCustomerRef",
    "SubscriptionRef",
    "InvoiceRef",
    "CheckoutSessionRequest",
    "CheckoutSessionResponse",
    "PortalSessionRequest",
    "PortalSessionResponse",
    "PaymentEvent",
    # Mailroom (shared service — PostGrid)
    "MailStatus",
    "MailClass",
    "MailReturnReason",
    "MailRecipient",
    "MailSender",
    "MailPacket",
    "MailDeliveryStatus",
    "MailReturnStatus",
    # RTC (shared service)
    "RTCRoomStatus",
    "RTCSession",
    "RTCParticipantToken",
    # Office Ally (shared service)
    "OfficeAllyEnrollmentStatus",
    "OfficeAllyEnrollment",
    "OfficeAllySubmission",
    "OfficeAllyResponse",
    # Device (shared service)
    "DevicePlatform",
    "DeviceStatus",
    "DeviceRegistration",
    # App Access (shared service)
    "AppAccessEffect",
    "AppAccessPolicy",
    "AppAccessDecision",
    # Shared platform primitives (Wave 0)
    # Human confirmation (primitive B)
    "DECIDED_DISPOSITIONS",
    "HumanConfirmationReceipt",
    "HumanDisposition",
    # Rule packs (primitive C)
    "MUTABLE_RULE_PACK_STATES",
    "RulePack",
    "RulePackRule",
    "RulePackState",
    # Provider adapters (primitive D)
    "RECONCILIATION_PROVIDER_STATES",
    "TERMINAL_PROVIDER_STATES",
    "ProviderOperationRecord",
    "ProviderOperationState",
    "ProviderRetryability",
    "ProviderTransportResult",
    # Exception inbox (primitive F)
    "TERMINAL_EXCEPTION_STATUSES",
    "ExceptionRecord",
    "ExceptionSeverity",
    "ExceptionStatus",
    # Protected-state conflicts (primitive G)
    "ProtectedStateKind",
    "ProtectedStateWrite",
    "StateConflict",
    # Outcome attribution (primitive K)
    "CAUSAL_ATTRIBUTION_METHODS",
    "AttributionMethod",
    "OutcomeAttribution",
    "OutcomeDefinition",
    "OutcomeDirection",
    "OutcomeObservation",
    # Offline authority (primitive J) - continuity_contracts
    "DIVERGENT_CONTINUITY_MODES",
    "ContinuityMode",
    "OfflineAuthorityGrant",
    "OfflineOperationEnvelope",
    # PHI-safe product telemetry (primitive L) - metrics_contracts
    "FORBIDDEN_TELEMETRY_DIMENSION_KEYS",
    "ProductTelemetryEvent",
    "TelemetryOutcome",
]
