"""ACIN provenance primitives — grounding and the fail-closed clinical claim.

Non-negotiable ACIN rules enforced here at the contract layer:

- Every generated clinical claim is grounded in at least one source field id.
  A claim with zero source references is INVALID (fail-closed — the contract
  refuses to construct it). ACIN never fabricates findings.
- AI-generated content always sets ``ai_generated=True`` and
  ``requires_human_review=True``. Nothing is auto-committed or auto-signed.
- Source references carry a redaction flag so PHI is never assumed safe to log.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator


class ACINSourceRef(BaseModel):
    """A reference to a source field that grounds an ACIN claim or section.

    Reuses the shape of ``adaptix_contracts.ai.capabilities.AISourceField`` so
    the redaction / prompt-inclusion semantics match the AI broker.
    """

    field_id: str = Field(
        ...,
        description=(
            "Stable source field identifier, e.g. a NEMSIS element ('eSituation.09') "
            "or a structured chart field ('epcr_vitals.<uuid>.heart_rate')."
        ),
    )
    source_model: Optional[str] = Field(
        default=None,
        description="Originating ORM/table name (e.g. 'epcr_vitals'), if applicable.",
    )
    source_pk: Optional[str] = Field(
        default=None,
        description="Primary key of the originating row, if applicable.",
    )
    observed_value_redacted: bool = Field(
        default=True,
        description="True when the observed value is redacted for logs/telemetry (no PHI).",
    )
    included_in_prompt: bool = Field(
        default=False,
        description="True when this field's value was included in the AI prompt context.",
    )

    model_config = ConfigDict(from_attributes=True)


class ACINProvenanceMixin(BaseModel):
    """Provenance carried by every generated ACIN section and claim.

    Enforces the ai_generated -> requires_human_review invariant at the contract
    boundary so no consumer can construct auto-accepted AI content.
    """

    ai_generated: bool = Field(
        ...,
        description="True when this content was produced by a model rather than a human.",
    )
    requires_human_review: bool = Field(
        default=True,
        description="Always True for ai_generated content — never auto-accepted.",
    )
    source_field_refs: list[ACINSourceRef] = Field(
        default_factory=list,
        description="Grounding source references for this content.",
    )
    model_name: Optional[str] = Field(
        default=None, description="Model that generated this content (attribution)."
    )
    model_version: Optional[str] = Field(
        default=None, description="Version of the generating model (attribution)."
    )
    capability_key: Optional[str] = Field(
        default=None,
        description="AI-Service capability key used to generate this content (attribution).",
    )

    @model_validator(mode="after")
    def _enforce_review_when_ai(self) -> "ACINProvenanceMixin":
        if self.ai_generated and not self.requires_human_review:
            raise ValueError(
                "ai_generated content must set requires_human_review=True "
                "(ACIN never auto-accepts AI output)"
            )
        return self

    model_config = ConfigDict(from_attributes=True)


class ACINClaimDTO(ACINProvenanceMixin):
    """A single grounded clinical/logic claim.

    A generated claim MUST cite at least one source field reference. This is the
    contract-level fail-closed guard against fabrication: constructing an
    ``ai_generated`` claim with no ``source_field_refs`` raises a ValidationError.
    """

    claim_id: str = Field(
        ..., description="Stable id for this claim within the record."
    )
    statement: str = Field(
        ...,
        description=(
            "The grounded claim text (e.g. a differential, a medical-necessity "
            "justification). Redaction of any embedded values is handled upstream."
        ),
    )
    # Generated by default; a human-authored claim can set ai_generated=False.
    ai_generated: bool = True
    requires_human_review: bool = True
    # Terminology grounding (optional; populated via Terminology-Service crosswalk).
    snomed_code: Optional[str] = None
    icd10_code: Optional[str] = None
    confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Model confidence 0.0-1.0, if available.",
    )

    @model_validator(mode="after")
    def _enforce_grounding(self) -> "ACINClaimDTO":
        if self.ai_generated and len(self.source_field_refs) < 1:
            raise ValueError(
                "ai_generated ACIN claim must cite at least one source_field_ref "
                "(no fabrication — a claim with zero refs is invalid)"
            )
        return self


__all__ = [
    "ACINSourceRef",
    "ACINProvenanceMixin",
    "ACINClaimDTO",
]
