"""Adaptix Community Paramedicine / MIH-CP contracts (Play P31).

Re-exports the models, enums, event names/payloads/envelope factories,
and service error contracts for the MIH-CP service, including the remote
patient monitoring and high-utilizer detection surface that
Adaptix-MIH-Service exposes under ``/api/v1/mih/patients/{id}/readings``,
``/thresholds``, ``/escalations`` and ``/api/v1/mih/utilization/*``.

``MIH_ENTITLEMENT_ID`` and ``MIH_SERVICE_AUDIENCE`` are the canonical
cross-repository identifiers used while the state-restricted MIH entitlement
is activated in Core and routed through Gateway. Keeping both values in the
shared contract package prevents Core, Gateway, and MIH from inventing their
own spellings while the broader module registry remains deliberately strict.
"""

from adaptix_contracts.mih.enums import (
    EnrollmentRecommendationStatus,
    EnrollmentStatus,
    HighUtilizerRecommendedAction,
    MihEscalationState,
    MihOutcomeType,
    MihPayer,
    MihReferralSource,
    MihServiceType,
    MihVisitStatus,
    RemoteReadingMetric,
    UtilizationEvaluationOrigin,
    UtilizationEventType,
    UtilizationPolicyStatus,
    UtilizationSourceSystem,
)
from adaptix_contracts.mih.errors import (
    MIH_SERVICE_ERROR_CODES,
    MihErrorCode,
    MihErrorEnvelope,
    MihServiceError,
    enrollment_consent_required,
    enrollment_not_found,
    from_service_error_code,
    payer_not_authorized_for_program,
    recommendation_invalid_transition,
    recommendation_not_found,
    to_adaptix_error_code,
    utilization_policy_not_configured,
    visit_invalid_state_transition,
)
from adaptix_contracts.mih.events import (
    MIH_DISCHARGED,
    MIH_ENROLLED,
    MIH_ENROLLMENT_RECOMMENDATION_CHANGED,
    MIH_EVENTS,
    MIH_HIGH_UTILIZER_EVALUATED,
    MIH_SOURCE_SERVICE,
    MIH_UTILIZATION_OBSERVATION_RECORDED,
    MIH_VISIT_COMPLETED,
    MIH_VISIT_SCHEDULED,
    MihDischargedPayload,
    MihEnrolledPayload,
    MihEnrollmentRecommendationChangedPayload,
    MihHighUtilizerEvaluatedPayload,
    MihUtilizationObservationRecordedPayload,
    MihVisitCompletedPayload,
    MihVisitScheduledPayload,
    build_mih_discharged_event,
    build_mih_enrolled_event,
    build_mih_enrollment_recommendation_changed_event,
    build_mih_high_utilizer_evaluated_event,
    build_mih_utilization_observation_recorded_event,
    build_mih_visit_completed_event,
    build_mih_visit_scheduled_event,
)
from adaptix_contracts.mih.models import (
    UTILIZATION_LOOKBACK_MAX_DAYS,
    UTILIZATION_LOOKBACK_MIN_DAYS,
    UTILIZATION_TRIGGER_SCORE_MAX,
    HighUtilizerSignal,
    expected_recommended_action,
    MihEnrollment,
    MihEnrollmentRecommendation,
    MihEscalation,
    MihMonitoringThreshold,
    MihOutcome,
    MihOutcomeMetric,
    MihProgram,
    MihProgramSchedule,
    MihRemoteReading,
    MihRemoteReadingBreach,
    MihServicePlan,
    MihServicePlanGoal,
    MihServicePlanIntervention,
    MihUtilizationCounts,
    MihUtilizationObservation,
    MihUtilizationPolicy,
    MihVisit,
    MihVisitLocation,
    MihVisitVitalSigns,
)

MIH_ENTITLEMENT_ID = "mih_community_paramedicine"
MIH_SERVICE_AUDIENCE = "adaptix-mih"

__all__ = [
    "EnrollmentRecommendationStatus",
    "EnrollmentStatus",
    "HighUtilizerRecommendedAction",
    "HighUtilizerSignal",
    "MIH_DISCHARGED",
    "MIH_ENROLLED",
    "MIH_ENROLLMENT_RECOMMENDATION_CHANGED",
    "MIH_ENTITLEMENT_ID",
    "MIH_EVENTS",
    "MIH_HIGH_UTILIZER_EVALUATED",
    "MIH_SERVICE_AUDIENCE",
    "MIH_SERVICE_ERROR_CODES",
    "MIH_SOURCE_SERVICE",
    "MIH_UTILIZATION_OBSERVATION_RECORDED",
    "MIH_VISIT_COMPLETED",
    "MIH_VISIT_SCHEDULED",
    "MihDischargedPayload",
    "MihEnrolledPayload",
    "MihEnrollment",
    "MihEnrollmentRecommendation",
    "MihEnrollmentRecommendationChangedPayload",
    "MihErrorCode",
    "MihErrorEnvelope",
    "MihEscalation",
    "MihEscalationState",
    "MihHighUtilizerEvaluatedPayload",
    "MihMonitoringThreshold",
    "MihOutcome",
    "MihOutcomeMetric",
    "MihOutcomeType",
    "MihPayer",
    "MihProgram",
    "MihProgramSchedule",
    "MihReferralSource",
    "MihRemoteReading",
    "MihRemoteReadingBreach",
    "MihServiceError",
    "MihServicePlan",
    "MihServicePlanGoal",
    "MihServicePlanIntervention",
    "MihServiceType",
    "MihUtilizationCounts",
    "MihUtilizationObservation",
    "MihUtilizationObservationRecordedPayload",
    "MihUtilizationPolicy",
    "MihVisit",
    "MihVisitCompletedPayload",
    "MihVisitLocation",
    "MihVisitScheduledPayload",
    "MihVisitStatus",
    "MihVisitVitalSigns",
    "RemoteReadingMetric",
    "UTILIZATION_LOOKBACK_MAX_DAYS",
    "UTILIZATION_LOOKBACK_MIN_DAYS",
    "UTILIZATION_TRIGGER_SCORE_MAX",
    "UtilizationEvaluationOrigin",
    "UtilizationEventType",
    "UtilizationPolicyStatus",
    "UtilizationSourceSystem",
    "build_mih_discharged_event",
    "build_mih_enrolled_event",
    "build_mih_enrollment_recommendation_changed_event",
    "build_mih_high_utilizer_evaluated_event",
    "build_mih_utilization_observation_recorded_event",
    "build_mih_visit_completed_event",
    "build_mih_visit_scheduled_event",
    "enrollment_consent_required",
    "enrollment_not_found",
    "expected_recommended_action",
    "from_service_error_code",
    "payer_not_authorized_for_program",
    "recommendation_invalid_transition",
    "recommendation_not_found",
    "to_adaptix_error_code",
    "utilization_policy_not_configured",
    "visit_invalid_state_transition",
]
